name: Homebrew Bump Cask PR


on:
  release:
    types: [released]

jobs:
  released:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew cask
        uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{secrets.BUMP_CASK_TOKEN}}
          tap: Homebrew/homebrew-cask
          cask: blobsaver